proxies:
proxy-groups:
  - name: "LLYCORIS"
    type: select
    use: [
        🌸
    ]
proxy-providers:
  🌸:
    type: file
    path: ./assets/akun.yaml
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
rules:
  - DOMAIN-SUFFIX,googlesyndication.com,LLYCORIS
  - AND,((DST-PORT,5228-5230),(NETWORK,TCP)),DIRECT
  - GEOSITE,CATEGORY-ADS-ALL,REJECT
  - MATCH,LLYCORIS